"""empty message

Revision ID: 1dbe16b6add8
Revises: 9ec93beee101
Create Date: 2016-11-13 20:02:14.118562

"""

# revision identifiers, used by Alembic.
revision = '1dbe16b6add8'
down_revision = '9ec93beee101'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('avg_price', sa.Integer(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination_stats')
    ### end Alembic commands ###
