"""empty message

Revision ID: 202d1c1b574b
Revises: 7763d6586173
Create Date: 2016-11-13 18:04:01.423284

"""

# revision identifiers, used by Alembic.
revision = '202d1c1b574b'
down_revision = '7763d6586173'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefered_airports')
    op.add_column('bid', sa.Column('dest_name', sa.String(length=35), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'dest_name')
    op.create_table('prefered_airports',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('name', mysql.CHAR(length=50), nullable=True),
    sa.Column('code', mysql.CHAR(length=3), nullable=True),
    sa.Column('country', mysql.CHAR(length=50), nullable=True),
    sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
