"""empty message

Revision ID: 662e16c5bc4e
Revises: 871563d1a216
Create Date: 2016-11-11 18:54:01.608313

"""

# revision identifiers, used by Alembic.
revision = '662e16c5bc4e'
down_revision = '871563d1a216'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('bid', sa.Column('found_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'found_at')
    op.drop_column('bid', 'distance')
    ### end Alembic commands ###
