"""empty message

Revision ID: 6c112e00f5ac
Revises: f8c4ba4afbfc
Create Date: 2016-11-11 18:25:30.770957

"""

# revision identifiers, used by Alembic.
revision = '6c112e00f5ac'
down_revision = 'f8c4ba4afbfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('price', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'price')
    ### end Alembic commands ###
