"""empty message

Revision ID: 711edb75f173
Revises: b5f9322993ee
Create Date: 2016-11-14 16:29:11.708576

"""

# revision identifiers, used by Alembic.
revision = '711edb75f173'
down_revision = 'b5f9322993ee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination_stats', sa.Column('total_bid_count', sa.Integer(), nullable=True))
    op.drop_column('destination_stats', 'bid_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination_stats', sa.Column('bid_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('destination_stats', 'total_bid_count')
    ### end Alembic commands ###
