"""empty message

Revision ID: 72db2bcaceeb
Revises: 98c48fcc6e14
Create Date: 2016-11-12 23:22:24.341661

"""

# revision identifiers, used by Alembic.
revision = '72db2bcaceeb'
down_revision = '98c48fcc6e14'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefered_airports')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefered_airports',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('name', mysql.CHAR(length=50), nullable=True),
    sa.Column('code', mysql.CHAR(length=3), nullable=True),
    sa.Column('country', mysql.CHAR(length=50), nullable=True),
    sa.Column('origin', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
