"""empty message

Revision ID: 7763d6586173
Revises: dc07d17cc383
Create Date: 2016-11-13 17:32:26.990282

"""

# revision identifiers, used by Alembic.
revision = '7763d6586173'
down_revision = 'dc07d17cc383'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefered_airports')
    op.add_column('bid', sa.Column('to_expose', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'to_expose')
    op.create_table('prefered_airports',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('name', mysql.CHAR(length=50), nullable=True),
    sa.Column('code', mysql.CHAR(length=3), nullable=True),
    sa.Column('country', mysql.CHAR(length=50), nullable=True),
    sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
