"""empty message

Revision ID: 871563d1a216
Revises: 6c112e00f5ac
Create Date: 2016-11-11 18:32:15.824903

"""

# revision identifiers, used by Alembic.
revision = '871563d1a216'
down_revision = '6c112e00f5ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('stops', sa.Integer(), nullable=True))
    op.add_column('bid', sa.Column('trip_class', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'trip_class')
    op.drop_column('bid', 'stops')
    ### end Alembic commands ###
