"""empty message

Revision ID: 98c48fcc6e14
Revises: 662e16c5bc4e
Create Date: 2016-11-12 14:49:23.221872

"""

# revision identifiers, used by Alembic.
revision = '98c48fcc6e14'
down_revision = '662e16c5bc4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('exposed', sa.Boolean(), nullable=True))
    op.add_column('bid', sa.Column('rating', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'rating')
    op.drop_column('bid', 'exposed')
    ### end Alembic commands ###
