"""empty message

Revision ID: 9ec93beee101
Revises: 202d1c1b574b
Create Date: 2016-11-13 18:07:17.952488

"""

# revision identifiers, used by Alembic.
revision = '9ec93beee101'
down_revision = '202d1c1b574b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=35), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination')
    ### end Alembic commands ###
