"""empty message

Revision ID: dc07d17cc383
Revises: 72db2bcaceeb
Create Date: 2016-11-12 23:22:57.410940

"""

# revision identifiers, used by Alembic.
revision = 'dc07d17cc383'
down_revision = '72db2bcaceeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('snapshot', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'snapshot')
    ### end Alembic commands ###
