"""empty message

Revision ID: f2252d3966c0
Revises: 584f857847d3
Create Date: 2016-11-16 13:41:28.333393

"""

# revision identifiers, used by Alembic.
revision = 'f2252d3966c0'
down_revision = '584f857847d3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_column('destination', 'number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination', sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('destination', 'score')
    ### end Alembic commands ###
