"""empty message

Revision ID: f8c4ba4afbfc
Revises: None
Create Date: 2016-11-11 17:44:22.971858

"""

# revision identifiers, used by Alembic.
revision = 'f8c4ba4afbfc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=3), nullable=True),
    sa.Column('destination', sa.String(length=3), nullable=True),
    sa.Column('search_date_in', sa.DateTime(), nullable=True),
    sa.Column('one_way', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=True),
    sa.Column('destination', sa.String(length=3), nullable=True),
    sa.Column('one_way', sa.Boolean(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('max_stops', sa.Integer(), nullable=True),
    sa.Column('query_type', sa.String(length=1), nullable=True),
    sa.Column('search_date_in', sa.DateTime(), nullable=True),
    sa.Column('search_date_out', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('departure_pm', sa.Integer(), nullable=True),
    sa.Column('return_pm', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=3), nullable=True),
    sa.Column('destination', sa.String(length=3), nullable=True),
    sa.Column('one_way', sa.Boolean(), nullable=True),
    sa.Column('trip_class', sa.Integer(), nullable=True),
    sa.Column('price_limit', sa.Integer(), nullable=True),
    sa.Column('price_unit', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_query')
    op.drop_table('bid')
    op.drop_table('ask')
    ### end Alembic commands ###
